# Generated by Django 2.2.6 on 2019-10-20 22:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30)),
                ('slug_name', models.SlugField(max_length=30)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(dim=3, geography=True, srid=4326, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
