# Generated by Django 2.2.6 on 2019-10-20 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peak',
            options={'verbose_name': 'peak', 'verbose_name_plural': 'Peaks'},
        ),
    ]
